{{ if and .Values.persistence.enabled (not .Values.backupVolume.existingClaimName) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etcd-backup
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.persistence.useDynamicProvisioning }}
  ## if present, use the storageClassName from the values.yaml, else use the
  ## default storageClass setup by kube Administrator
  ##
  ## setting storageClassName to nil means use the default storage class
  storageClassName: {{ default nil .Values.backupVolume.storageClassName | quote }}
  {{- else }}
  ## disable dynamic provisioning
  storageClassName: ""
  {{- end }}

  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.backupVolume.size | quote }}
{{- end }}


