## Metadata for IBM DSM configuration
## This metadata is used to augment the value.yaml to drive ICP UI for configuration of the Helm chart installation

## Image configuration metadata
image:
  __metadata:
    label: "Docker image configuration"
  repository:
    __metadata:
      name: "Repository"
      label: "Docker Repository"
      description: "Docker registry to pull image from."
      type: "string"
      immutable: false
      required: true
  tag:
    __metadata:
      name: "tag"
      label: "Docker image version"
      description: "Docker image version."
      type: "string"
      immutable: false
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
      type: "string"
      immutable: false
      required: true
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"

## Data volume claim options
backupVolume:
  __metadata:
    label: "Backup volume configuration"
  name:
    __metadata:
  existingClaimName:
    __metadata:
      name: "existingClaimName"
      label: "Existing volume claim"
      description: "By default a new persistent volume claim will be created. Specify an existing claim here if one is available."
      type: "string"
      immutable: false
      required: false
  storageClassName:
    __metadata:
      name: "storageClassName"
      label: "Existing storage class name"
      description: "Choose a specific storage class name. Defaults to the default storage class in the cluster."
      type: "string"
      immutable: false
      required: false
  size:
    __metadata:
      name: "size"
      label: "Size of the volume claim"
      description: "Defaults to 1Gi of storage request. Choose a different size of disk if needed."
      type: "string"
      immutable: false
      required: true

## Persistence options
persistence:
  __metadata:
    label: "Backup persistence configuration"
  enabled:
   __metadata:
      name: "enabled"
      label: "Enable persistence for this deployment"
      description: "Enables persistence for this deployment. Defaults to true. A persistent volume is required."
      type: "boolean"
      immutable: false
      required: true
  useDynamicProvisioning:
   __metadata:
      name: "useDynamicProvisioning"
      label: "Use dynamic provisioning for persistent volume"
      description: "If dynamic provisioning is available in the cluster this option will automatically provision the requested volume if set to true. Defaults to false."
      type: "boolean"
      immutable: false
      required: true
## Backup options
backupParameters:
  __metadata:
    label: "Backup schedule and retention parameters"
  backupSchedule:
    __metadata:
      name: "backupSchedule"
      label: "Backup schedule"
      description: "Backup schedule in crontab format for exmaple: 00 00 * * * will run the job everyday at 00:00" 
      type: "string"
      immutable: false
      required: true
  backupRetention:
    __metadata:
      name: "backupRetention"
      label: "Backup retention"
      description: "for how long to save the backup files, each time the job runs it deletes older backups"
      type: "number"
      immutable: false
      required: true